 version: 2
 jobs:
  test-build-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            # テスト
            - run: yarn test
            # ビルド
            - run: yarn build
            # cliからNetlifyにデプロイできるようにするライブラリをインストール
            - run: yarn add netlify-cli
            # デプロイ（詳細は後述します）
            - run: yarn netlify deploy -p -d jobs -a ${NETLIFY_AUTH_TOKEN} -s ${NETLIFY_SITE_ID}
